### ISSUE TITLE
Placing controllers in views/ folder

### ISSUE THREAD

**Issue by leewardbound** [piercefreeman/mountaineer#118]
Hi there, I've adopted a QOL convention of placing my controllers in the `views/` folder, next to their respective page.tsx.

However I've noticed that controller hotloading is broken when I do this. I ran some tests with the `ci_webapp` folder on latest main branch and found the following:

+ Controllers can be placed in any folder (other than `controllers/`) and hotloading still works
+ But if you place them in the `views/` folder, hotloading stops working
+ To test this:
  + start the debug server and open the `/` root, then modify home.py to add `print("foo")` to the render() method - the page will reload and "foo" will print appropriately
  + now move home.py to views/app/home/ (my IDE automatically creates 3 levels of `__init__.py` files in the parent folders), restart the dev server, and change "foo" to "bar", - the page will not reload, and if you refresh, "foo" will still appear.
  
I recognize that colocating the JS and python in the same folder is unconventional, but mountaineer is unconventional :) I think this pattern makes a lot of sense - since the Controller enforces that the page must be named "page.tsx", it's also enforcing 1 page per directory, and I noticed my `controllers/` directory tree was essentially mirroring the shape of the `views/` directory.

Is there a necessary reason why putting a Controller in the `views/` folder breaks hotloading? Could this be supported in the future?

**Comment by piercefreeman** [comment]
@leewardbound The views folder is internally flagged to only support js-based hot reloading, where we don't need to restart the backend server and can instead just rebuild the js files and push them to connected clients. See here:

https://github.com/piercefreeman/mountaineer/blob/main/mountaineer/cli.py#L188
https://github.com/piercefreeman/mountaineer/blob/main/mountaineer/cli.py#L314
https://github.com/piercefreeman/mountaineer/blob/main/mountaineer/cli.py#L480

On a deeper level - keeping the frontend code isolated within the folder convention lets node "own" the whole view folder, so you're able to put package.json specifications alongside postcss, eslint, etc. Node/npm defacto expects to have ownership of its nested folder so it can add dynamic files in there. Adding python controllers to this mix is just too messy and might have longterm behavior conflicts.

**Comment by leewardbound** [comment]
Thanks for the quick reply, makes sense to me!
