### ISSUE TITLE
more docs and info on the architecture?

### ISSUE THREAD

**Issue by CJHarmath** [piercefreeman/mountaineer#48]
Do you have more docs, blogs or a podcast, etc covering the architecture, choosing rust, etc how did you end up here?
I am just curious to learn more about those details.
The current readmes jump straight into the details and the guides, which are awesome, but I was also wondering the big picture and the story behind too. For example the v8 engine part, going with rust, etc. It could make up a nice reading or a podcast, at least to me.
Thanks and feel free to close this issue as it's not really an issue, just curiosity.

**Comment by piercefreeman** [comment]
@CJHarmath Definitely planning on making more content on the architecture. Is the top of your list specifically the V8 engine & rust? Anything else I should consider that's top of mind?

**Comment by CJHarmath** [comment]
I mean the whole thing is fascinating to me honestly. 
how did you end up with the useServer, side effects, the typing system, server side rendering, code generation etc.
But also your tooling is new and custom to me. such as the cli, the watcher web service etc. It has a lot of cool stuff added on top of FastAPI.
Have you actually considered to work with the FastAPI author to add some of these features to FastAPI?

I've been looking at FastAPI with it's Pydantic schemas and were thinking about looking at UI generation based on the schema of the API with perhaps some UI schema such as https://github.com/rjsf-team/react-jsonschema-form
Were also looking at micro UIs, etc various topics and trying to come up with a way to generate UIs in a Python backend dev friendly way (mostly just on a hobby level, and didn't get anywhere yet)
Were thinking of having:
- a list of components for generic things with their schemas (forms, searchable grids, etc mostly for crud)
-  backend being able to send back the data + UI component schema required to generate the UI
- generic frontend to generate the UI 
- then saw htmx
- and now this :)

but this is a whole different level of thinking about things and plumbing things together.
To me it's a brand new novel approach, very innovative and I just want to learn more about the details.

btw, how do you setup your VSCode for debugging?

**Comment by piercefreeman** [comment]
@CJHarmath I opened a general ticket to track documentation improvements. Feel free to chime there with more specifics: https://github.com/piercefreeman/mountaineer/issues/60

In the meantime I'm also working on a few followup blog posts and some YouTube tutorials. Chime there (or feel free to reopen this ticket) if you have other items on your list.
