### ISSUE TITLE
After simple setup: Missing mandatory keyword argument 'view_root' in constructor call

### ISSUE THREAD

**Issue by hoetmaaiers** [piercefreeman/mountaineer#77]
I followed the simple setup as documented in the README but bump into this error when doing `poetry run runserver`. 

Error:
`Missing mandatory keyword argument 'view_root' in constructor call`

**Comment by piercefreeman** [comment]
Hey @hoetmaaiers thanks for the report. What version of mountaineer / create-mountaineer-app are you using? If you're in a poetry environment you should be able to run:

```
poetry run pip freeze | grep mountaineer
```

**Comment by piercefreeman** [comment]
I'm seeing that CMA is still pinned to version 0.1.x. Will push a patch for this in a second. In the meantime, you should be able to unblock yourself by modifying the `pyproject.toml` to pull the latest released version. In this version we removed the need to explicitly provide view_root.

```
[tool.poetry.dependencies]
python = "^3.11"
mountaineer = "^0.2.0"
```

**Comment by hoetmaaiers** [comment]
So no need to rerun the `pipx create xxx` step?

**Comment by piercefreeman** [comment]
No, just bump your pyproject.toml and bump the poetry deps:

```bash
vi pyproject.toml
poetry lock
poetry install
poetry run runserver
```

**Comment by hoetmaaiers** [comment]
sorry, just removed my comment about rerunning using `pipx run create-mountaineer-app`

**Comment by piercefreeman** [comment]
I also just pushed a beta that shouldn't require this manual workaround anymore. This will land in the stable 0.3.0, which should drop in the next couple days or so. In the meantime, you can try the new CMA via the pre-release.

```bash
pipx run create-mountaineer-app==0.3.0.dev2
```
